[package]
name = "reputation-system"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
doctest = false

[dependencies]
soroban-sdk = { workspace = true }
nft-core = { path = "../nft-core" }

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }
