[package]
name = "recognition-system"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
doctest = false

[dependencies]
soroban-sdk = { workspace = true }
reputation-system = { path = "../reputation-system" }

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }

